### PR TITLE
fix(webpack): fix error when cacheProvider is undefined

### PR DESCRIPTION
**Pull request by malash**
## Motivation

While cherry picking `cacheProvider` to Linaria v3 I found a same bug in https://github.com/callstack/linaria/pull/884

## Summary

If `cacheProvider` is not set ( `undefined` ), the query param `cacheProvider=${encodeURIComponent(cacheProvider)}`  became a string `'undefined'` and result in a runtime error `Cannot find module 'undefined'`.

## Test plan

I'v test `cacheProvider: undefined` in https://github.com/callstack/linaria/pull/889

### CODE REVIEW

**Comment by malash** [comment]
@Anber Could you mind public a new version of Linaria v2, since this bug would affect most of normal Linaria users.

**Comment by Anber** [comment]
Hi @malash 
I would like to, but there is a big issue #891 introduced in #879. I have to fix it first.
