### ISSUE TITLE
Typings not working when overriding another `styled` component

### ISSUE THREAD

**Issue by OrcaXS** [callstack/linaria#622]
## Environment

Linaria version: 2.0.0-alpha.5
Bundler (+ version): webpack 4.43.0
Node.js version: v12.16.3
OS: macOS 10.15.4
React: 16.13.1

## Description
Annotating props of a `styled` component works fine like in #536:
```tsx
const Wrapper = styled.div<{ compose: boolean }>`
  width: 1em;
  background-color: ${(props) => (props.compose ? 'transparent' : 'green')};
`
```
But doesn't work on an overrode one:
```tsx
const NewWrapper = styled(Wrapper)<{ compose: boolean }>`
  width: 2em;
  background-color: ${(props) => (props.compose ? 'transparent' : 'green')};
`
```

Errors are like below:
```
Argument of type '(props: any) => any' is not assignable to parameter of type 'StaticPlaceholder'.
  Property '__linaria' is missing in type '(props: any) => any' but required in type 'StyledMeta'.ts(2345)
types.ts(47, 3): '__linaria' is declared here.
```

Am I annotating the types the wrong way? Thanks.

## Reproducible Demo
```tsx
import React from 'react';
import { styled } from 'linaria/react';

const Wrapper = styled.div<{ compose: boolean }>`
  width: 1em;
  background-color: ${(props) => (props.compose ? 'transparent' : 'green')};
`

const NewWrapper = styled(Wrapper)<{ compose: boolean }>`
  width: 2em;
  background-color: ${(props) => (props.compose ? 'transparent' : 'red')};
`

const App = () => (
  <NewWrapper compose>Test</NewWrapper>
);
```

**Comment by TMaszko** [comment]
Hi! Could you provide a complete repo where we can reproduce this bug :)?`
Thanks in advance !

**Comment by OrcaXS** [comment]
Sure, here it is! 
https://github.com/OrcaXS/linaria-issue-reproduce/tree/typescript-styled-override


Running `yarn tsc` throws:
```
src/index.tsx:11:23 - error TS2345: Argument of type '(props: any) => "transparent" | "red"' is not assignable to parameter of type 'StaticPlaceholder'.
  Property '__linaria' is missing in type '(props: any) => "transparent" | "red"' but required in type 'StyledMeta'.

11   background-color: ${(props) => (props.compose ? 'transparent' : 'red')};
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/linaria/lib/types.d.ts:43:5
    43     __linaria: {
           ~~~~~~~~~
    '__linaria' is declared here.
  src/index.tsx:11:23
    11   background-color: ${(props) => (props.compose ? 'transparent' : 'red')};
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to call this expression?

src/index.tsx:11:24 - error TS7006: Parameter 'props' implicitly has an 'any' type.

11   background-color: ${(props) => (props.compose ? 'transparent' : 'red')};
                          ~~~~~


Found 2 errors.
```

**Comment by jayu** [comment]
I tried this one today... Our types for styled are very mysterious :P For sure we should separate types that are valid internally for linaria during the build, and types that are exposed to the end-user after the build, because currently they are mixed together. 

If I had more time I would try implementing types from scratch and probably based on typing from `styled-components` or `emotion`. There is quite hard types interference issue to solve

**Comment by Pytal** [comment]
@jayu if the api for linaria v2 is the same as v1 then wouldn't the typings be the same?

**Comment by jayu** [comment]
@Pytal It's a bit complicated because the internals changes and affected the typings. In fact, the change of internals shouldn't affect it. @Pytal let me know which version has correct typings and I will take a look on that! is it `1.3.x`?

**Comment by Pytal** [comment]
@jayu yeah typings work on `1.3.3`

**Comment by Anber** [comment]
Fixed in #639
