### ISSUE TITLE
react-spring/web styled(animated.div) stops working from 4.0.0-beta.0

### ISSUE THREAD

**Issue by chentsulin** [callstack/linaria#1140]
## Environment

- Linaria version: 4.0.0-beta.0~4.2+
- Bundler (+ version): Next.js 13.0.2
- Node.js version: v18.12.1
- OS: macOS 12 

## Description

Using Linaria with react-spring/web `animated.div`:

```jsx
import { styled } from '@linaria/atomic';
import { animated } from '@react-spring/web';

const Container = styled(animated.div)`
  max-width: 500px;
`;
```

It throws an eval error

```
/Users/chentsulin/project/node_modules/@linaria/babel-preset/lib/module.js:391
        throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
        ^

EvalError: exports.hasOwnProperty is not a function in
| /Users/chentsulin/project/node_modules/@react-spring/web/dist/react-spring-web.cjs.prod.js
| /Users/chentsulin/project/node_modules/@react-spring/web/dist/react-spring-web.cjs.js
```

The snippet in the `react-spring-web.cjs.prod.js` file:

```js
Object.keys(core).forEach(function (k) {
  if (k !== 'default' && !exports.hasOwnProperty(k)) Object.defineProperty(exports, k, {
    enumerable: true,
    get: function () { return core[k]; }
  });
});
```

This usage works with Linaria v3.0.0-beta.22 and stops working from v4.0.0-beta.0.

**Comment by Anber** [comment]
Oh… well. I guess we have [the same problem](https://github.com/callstack/linaria/pull/1138) here. I should have added rollup/esbuild as well to that PR.

**Comment by hazzo** [comment]
It's still this an issue? I'm having a similar error with react-spring. It only happens at build time.

```
[linaria] Cannot set properties of undefined (setting 'batchedUpdates') in
| /Users/guido/Documents/Develop/react_base/node_modules/@react-spring/web/dist/react-spring-web.esm.js
| /Users/guido/Documents/Develop/react_base/src/ui/components/modal/modal.styled.ts

file: /Users/guido/Documents/Develop/react_base/src/ui/components/modal/modal.styled.ts
error during build:
/Users/guido/Documents/Develop/react_base/node_modules/@linaria/babel-preset/lib/module.js:362
      throw new EvalError(`${e.message} in${callstack.join('\n| ')}\n`);
      ^

EvalError: Cannot set properties of undefined (setting 'batchedUpdates') in
| /Users/guido/Documents/Develop/react_base/node_modules/@react-spring/web/dist/react-spring-web.esm.js
| /Users/guido/Documents/Develop/react_base/src/ui/components/modal/modal.styled.ts
```

**Comment by Anber** [comment]
Hi @hazzo 
Everything should be ok. Could you please try to create a repo that reproduces the problem?
